### ISSUE TITLE
error 404 при выходе пользователя с сайта

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#141]
Логинишься, потом жмёшь "Выход", и страница https://hackerspace.by/users/sign_out тебе говорит "
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved."

**Comment by yahor** [comment]
@jekhor не магу паўтарыць, можа быць у цябе не справацаў метад пост?

павінен быць быць метад пост ў запыце і параметар _method=delete

js уключаны ў браўзеры?

**Comment by jekhor** [comment]
On Mon, Feb 20, 2017 at 11:47:46AM -0800, Yahor wrote:
> @jekhor не магу паўтарыць, можа быць у цябе не справацаў метад пост?
> 
> павінен быць быць метад пост ў запыце і параметар _method=delete
> 
> js уключаны ў браўзеры?

Цікава, уключыў дэбагер — спрацавала. Можа, штосьці закэшавалася...

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/hackerspace.by/issues/141#issuecomment-281167042

-- 
Yauhen Kharuzhy

**Comment by jekhor** [comment]
On Mon, Feb 20, 2017 at 11:47:46AM -0800, Yahor wrote:
> @jekhor не магу паўтарыць, можа быць у цябе не справацаў метад пост?
> 
> павінен быць быць метад пост ў запыце і параметар _method=delete
> 
> js уключаны ў браўзеры?

А зараз не спрацавала... Ідзе GET https://hackerspace.by/users/sign_out


> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/hackerspace.by/issues/141#issuecomment-281167042

-- 
Yauhen Kharuzhy

**Comment by jekhor** [comment]
```

I, [2017-02-20T23:05:17.228785 #32428]  INFO -- : Started GET "/users/sign_out" for 46.53.203.243 at 2017-02-20 23:05:17 +0300
F, [2017-02-20T23:05:17.230540 #32428] FATAL -- :   
F, [2017-02-20T23:05:17.230695 #32428] FATAL -- : ActionController::RoutingError (No route matches [GET] "/users/sign_out"):
F, [2017-02-20T23:05:17.230794 #32428] FATAL -- :   

```

**Comment by jekhor** [comment]
Нават так:
```
I, [2017-02-20T23:05:11.146654 #32428]  INFO -- : Started GET "/users/sign_in" for 46.53.203.243 at 2017-02-20 23:05:11 +0300
I, [2017-02-20T23:05:11.148541 #32428]  INFO -- : Processing by Devise::SessionsController#new as HTML
I, [2017-02-20T23:05:11.283960 #32428]  INFO -- :   Rendering devise/sessions/new.html.haml within layouts/application
I, [2017-02-20T23:05:11.287064 #32428]  INFO -- :   Rendered devise/shared/_links.html.haml (0.1ms)
I, [2017-02-20T23:05:11.287235 #32428]  INFO -- :   Rendered devise/sessions/new.html.haml within layouts/application (3.1ms)
I, [2017-02-20T23:05:11.290271 #32428]  INFO -- :   Rendered layouts/_og_meta_tags.html.haml (2.1ms)
I, [2017-02-20T23:05:11.290907 #32428]  INFO -- :   Rendered shared/_google_analytics.html.haml (0.3ms)
I, [2017-02-20T23:05:11.292813 #32428]  INFO -- :   Rendered layouts/_navigation.html.haml (1.7ms)
I, [2017-02-20T23:05:11.294297 #32428]  INFO -- : Completed 200 OK in 146ms (Views: 11.0ms | ActiveRecord: 0.0ms)
I, [2017-02-20T23:05:13.962675 #32428]  INFO -- : Started POST "/users/sign_in" for 46.53.203.243 at 2017-02-20 23:05:13 +0300
I, [2017-02-20T23:05:13.963949 #32428]  INFO -- : Processing by Devise::SessionsController#create as HTML
I, [2017-02-20T23:05:13.964053 #32428]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"r20R1JIxyUWMhjfJ0QN2/aaBuYjFcqL5kdNnIGe8OCgw01r6wpVcLYUK7Kb05l3YVM0fRn4bflRGumdSzZ7QAA==", "user"=>{"email"=>"jekhor@gmail.com", "password"=>"[FILTERED]"}, "commit"=>"Войти"}
I, [2017-02-20T23:05:14.208336 #32428]  INFO -- : Redirected to https://hackerspace.by/
I, [2017-02-20T23:05:14.208557 #32428]  INFO -- : Completed 302 Found in 244ms (ActiveRecord: 0.0ms)
I, [2017-02-20T23:05:14.265263 #32428]  INFO -- : Started GET "/" for 46.53.203.243 at 2017-02-20 23:05:14 +0300
I, [2017-02-20T23:05:14.266351 #32428]  INFO -- : Processing by MainController#index as HTML
I, [2017-02-20T23:05:14.386610 #32428]  INFO -- :   Rendering main/index.html.haml within layouts/application
I, [2017-02-20T23:05:14.393284 #32428]  INFO -- :   Rendered main/index.html.haml within layouts/application (6.5ms)
I, [2017-02-20T23:05:14.396101 #32428]  INFO -- :   Rendered layouts/_og_meta_tags.html.haml (2.2ms)
I, [2017-02-20T23:05:14.396966 #32428]  INFO -- :   Rendered shared/_google_analytics.html.haml (0.4ms)
I, [2017-02-20T23:05:14.403395 #32428]  INFO -- :   Rendered layouts/_navigation.html.haml (6.2ms)
I, [2017-02-20T23:05:14.405310 #32428]  INFO -- : Completed 200 OK in 139ms (Views: 19.0ms | ActiveRecord: 0.0ms)
I, [2017-02-20T23:05:17.228785 #32428]  INFO -- : Started GET "/users/sign_out" for 46.53.203.243 at 2017-02-20 23:05:17 +0300
F, [2017-02-20T23:05:17.230540 #32428] FATAL -- :   
F, [2017-02-20T23:05:17.230695 #32428] FATAL -- : ActionController::RoutingError (No route matches [GET] "/users/sign_out"):
F, [2017-02-20T23:05:17.230794 #32428] FATAL -- :   
F, [2017-02-20T23:05:17.230883 #32428] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
F, [2017-02-20T23:05:17.230966 #32428] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
F, [2017-02-20T23:05:17.231047 #32428] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
F, [2017-02-20T23:05:17.231124 #32428] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
F, [2017-02-20T23:05:17.231205 #32428] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
F, [2017-02-20T23:05:17.231290 #32428] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
F, [2017-02-20T23:05:17.231373 #32428] FATAL -- : activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
F, [2017-02-20T23:05:17.231458 #32428] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
F, [2017-02-20T23:05:17.231540 #32428] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
F, [2017-02-20T23:05:17.231619 #32428] FATAL -- : rack (2.0.1) lib/rack/method_override.rb:22:in `call'
F, [2017-02-20T23:05:17.231696 #32428] FATAL -- : rack (2.0.1) lib/rack/runtime.rb:22:in `call'
F, [2017-02-20T23:05:17.231781 #32428] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
F, [2017-02-20T23:05:17.231928 #32428] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
F, [2017-02-20T23:05:17.232010 #32428] FATAL -- : rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
F, [2017-02-20T23:05:17.232091 #32428] FATAL -- : railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
F, [2017-02-20T23:05:17.232168 #32428] FATAL -- : puma (3.6.0) lib/puma/configuration.rb:225:in `call'
F, [2017-02-20T23:05:17.232244 #32428] FATAL -- : puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
F, [2017-02-20T23:05:17.232318 #32428] FATAL -- : puma (3.6.0) lib/puma/server.rb:415:in `process_client'
F, [2017-02-20T23:05:17.232391 #32428] FATAL -- : puma (3.6.0) lib/puma/server.rb:275:in `block in run'
F, [2017-02-20T23:05:17.232459 #32428] FATAL -- : puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'

```

**Comment by yahor** [comment]
такое адчуванне што не спрацоўвае джаваскрыпт не спрацоўвае
правер што няма памылак у кансолі і падлучаецца jquery_ujs

**Comment by jekhor** [comment]
Не атрымліваецца паўтарыць зноўку... Дык а нахалеры яно праз JS гэта робіць?

**Comment by yahor** [comment]
@jekhor 

Rails guides: Here we're using link_to in a different way. We pass the named route as the second argument, and then the options as another argument. The method: :delete and data: { confirm: 'Are you sure?' } options are used as HTML5 attributes so that when the link is clicked, Rails will first show a confirm dialog to the user, and then submit the link with method delete. This is done via the JavaScript file jquery_ujs which is automatically included in your application's layout (app/views/layouts/application.html.erb) when you generated the application. Without this file, the confirmation dialog box won't appear.

+ не трэба пісаць нейкія формы для метада делете
