### ISSUE TITLE
Непубличная новость

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#147]
Новость ломается когда при создании новости не стоит галка публичная.
Ее потом нельзя редактировать/удалить.

app/controllers/news_controller.rb:69:in `set_news'

```
Couldn't find News with 'id'=15 [WHERE "news"."public" = $1]

    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.published.find(params[:id])
      if @news.public or @news.user == current_user
        @news
      else

Rails.root: /Work/mxc/github/hackerspace
Application Trace | Framework Trace | Full Trace
activerecord (5.0.0.1) lib/active_record/relation/finder_methods.rb:357:in `raise_record_not_found_exception!'
activerecord (5.0.0.1) lib/active_record/relation/finder_methods.rb:477:in `find_one'
activerecord (5.0.0.1) lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
activerecord (5.0.0.1) lib/active_record/relation/finder_methods.rb:66:in `find'
app/controllers/news_controller.rb:69:in `set_news'
```

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/pull/157
